### ISSUE TITLE
Cyan Light theme is not working.

### ISSUE THREAD

**Issue by wooowchik** [bIaqat/cyan-light-theme-zed#1]
I applied the Cyan Light theme as described in the instructions, but the final result has absolutely nothing to do with what is supposed to be.
![zedcreep](https://github.com/user-attachments/assets/05570e04-0a3b-4292-bb18-d6d5a27b2952)

Meanwhile this - How is supposed to look like:
https://raw.githubusercontent.com/bIaqat/cyan-light-theme-zed/main/assets/cyan-light.png

**Comment by blaqat** [comment]
That looks correct, just on the wrong version. 
I pushed an update (3cb1d2a97393f9451d36aa76675f4a5f3b8d75d0) to the yellow function name a couple days ago. 

You can also search and use the extension to have the up to date version. 
![Zed Preview-zed-themes-Capture-019064](https://github.com/user-attachments/assets/db2d6823-5186-4332-b823-1d3f0bff6927)

**Comment by wooowchik** [comment]
Perfect, now everything seems to work :)
![Screenshot from 2024-07-31 11-19-42](https://github.com/user-attachments/assets/b57656c2-881d-4f2d-b63c-0eece61c06f0)
